### ISSUE TITLE
write tests for delay node

### ISSUE THREAD

**Issue by malikbeytrison** [ebu/ebu-tt-live-toolkit#233]

**Comment by EyalLavi** [comment]
Provisionally assigning this to R4 although we may decide that variable delay can be added in a later release.

**Comment by nigelmegitt** [comment]
R4 is correct since the delay node component is an R4 objective, and we need to make sure it is tested.

**Comment by nigelmegitt** [comment]
This is pending PR merge (#305).

**Comment by nigelmegitt** [comment]
Looking at spec-conformance post merge of #305 there are several requirements not yet tested, specifically R109-R117, or at least the BDDs for those are not on the file, so this is not actually ready yet.

**Comment by nigelmegitt** [comment]
As part of #351 (specifically in 11ba71f214ac7cba106ebe97179111f3a9d60b63 and 5feb3cb) I have moved the skipped buffer delay node sequence number identity scenario out of the retiming delay node feature file and changed the comment to reflect that this now needs to test for document identity on emission rather than sequence number identity, ideally using `deep-equals` but forgivably using a lesser test.

**Comment by EyalLavi** [comment]
@kozmaz87 could you please review https://github.com/ebu/ebu-tt-live-toolkit/commit/a8305a6f5532a98cc892c0f77465722186d6df0a as we discussed yesterday?
