### ISSUE TITLE
[DELAY NODE] implicit -> explicit conversion for RetimingDelayNode

### ISSUE THREAD

**Issue by malikbeytrison** [ebu/ebu-tt-live-toolkit#291]

**Comment by nigelmegitt** [comment]
I thought we had this logged better but I cannot find it now.

The issue here is that the current logic (which I provided, in summary form) has the feature of elegantly making minimal changes to explicitly timed documents, but does not handle content that is implicitly timed, i.e. where there is a path from root to leaf that has no `begin` attributes on it at all.

This is interpreted in TTML as the begin of all elements is at time "zero" on the document's timeline. The only thing we can sensibly do here is add a `begin` attribute somewhere - the simplest place to do it is on the `body` element.

So a document like:

```xml
<tt>
<head>...</head>
<body>
   <div>
      <p>Some implicitly timed text</p>
      <p begin="00:00:20">Some explicitly timed text</p>
   </div>
</body>
```

will by the current algorithm, if delaying by say, 5s, be changed to:

```xml
<tt>
<head>...</head>
<body>
   <div>
      <p>Some implicitly timed text</p>
      <p begin="00:00:25">Some explicitly timed text</p>
   </div>
</body>
```

whereas by proper TTML interpretation it should be changed to :

```xml
<tt>
<head>...</head>
<body begin="00:00:05">
   <div>
      <p>Some implicitly timed text</p>
      <p begin="00:00:20">Some explicitly timed text</p>
   </div>
</body>
```

This means unfortunately that if there are _any_ untimed leaf elements then the best solution is _only_ to modify the `body` element to add a `begin` attribute whose value is the same as the delay value. If the `body` element has an `end` attribute that should changed to its previous value plus the delay value.

If this scenario arises then the existing logic must _not_ run because it will add the delay twice.

**Comment by malikbeytrison** [comment]
I'm somehow confused. @nigelmegitt you said

> [...] implicitly timed, i.e. where there is a path from root to leaf that has no begin attributes on it at all.

and that the current algorithm applies the delay as described. But the document that you take as example is explicitly timed due to the begin attribute in the `p` element, right? So in this case, the current algorithm looks fine to me. If the document didn't have any timing at all, then I would agree that we would add the delay value as begin time of the body.

> This means unfortunately that if there are any untimed leaf elements then the best solution is only to modify the body element to add a begin attribute whose value is the same as the delay value. If the body element has an end attribute that should changed to its previous value plus the delay value.

I agree with this, but I don't think it would apply to the very specific example you showed. For me, this document is explicitly timed.

**Comment by malikbeytrison** [comment]
I committed for the update of body begin time in dbf1423.

**Comment by nigelmegitt** [comment]
It's probably misleading to focus on implicitly timed vs explicitly timed. There's no practical difference in TTML/SMIL semantics between:

```xml
<tt>
...
<body><div><p>Text</p></div></body>
</tt>
```

and

```xml
<tt>
...
<body begin="00:00:00"><div><p>Text</p></div></body>
</tt>
```

In the example I gave I think your function `is_explicitly_timed` returns `true` whereas it should return `false` - it needs to check that _all_ the children are explicitly timed not what it currently does, which is to check if `any` of the children is explicitly timed. So it is currently possible to have an untimed root to leaf path that does not get modified, but in this case we should be updating the body begin time.

Also, `update_body_timing` should check if there is an `end` attribute on the `body` and modify that (add the delay offset) if it exists.

**Comment by nigelmegitt** [comment]
This has just been done by merging #301 - closing.
