### ISSUE TITLE
Resolve the two requirements sets

### ISSUE THREAD

**Issue by nigelmegitt** [ebu/ebu-tt-live-toolkit#306]
We have requirements listed at  ebu-tt-live-toolkit/testing/SPEC-CONFORMANCE.md  and also in the wiki page https://github.com/ebu/ebu-tt-live-toolkit/wiki/EBU-Tech-3350,-3370-&-3380-conformance-requirements and they don't agree with each other, in that the requirements with the same number have different text and origins.

This needs to be resolved, because it's very confusing! And unnecessary.

With apologies for landing you with this mess, assigning to @EyalLavi . I think everyone has been working against SPEC-CONFORMANCE.md so that might help...

**Comment by nigelmegitt** [comment]
Is this now done? It may be done in the wiki in which case there will be no commit reference.

**Comment by EyalLavi** [comment]
Actions following discussion yesterday:
- a Notice that the pages are not up to date with 3380 added to https://github.com/ebu/ebu-tt-live-toolkit/wiki/EBU-Tech-3350,-3370-&-3380-conformance-requirements and https://github.com/ebu/ebu-tt-live-toolkit/wiki/EBU-TT-Part-3-to-TT-D-conversion-requirements
-  Numbering scheme modified so that each list is prefixed with a different letter
- `EBU-TT-Part-3-to-TT-D-conversion-requirements` generated errors in Github so was converted from Wiki to Markdown markup. 
- TODO: align `EBU-TT-Part-3-to-TT-D-conversion-requirements` with `SPEC-CONFORMANCE.md`

**Comment by EyalLavi** [comment]
An additional task was split into #345. This ticket can be closed now.

**Comment by nigelmegitt** [comment]
Thanks, closing.
