### ISSUE TITLE
Wire in duplicate sequence number BDDs

### ISSUE THREAD

**Issue by nigelmegitt** [ebu/ebu-tt-live-toolkit#349]
We have `segmentation/duplicate_sequence_id+nun.feature` but it is not wired in with any code. Needs wiring in so it runs.

**Comment by kozmaz87** [comment]
Ok I will create a new task branch for this one and do it there.

**Comment by kozmaz87** [comment]
This one was left unwired because the request is that the websocket should be fully functional during the BDD tests but I am yet to find a way to get a reactor safely going and stop it after the test is finished. The clock reactor may be also a decent solution. The reason is that without an event loop that implements the IReactor interface the data would never be lifted into the TCP stack and would never be lifter out from there so the application would not propel its dataflow pipelines. The unittesting uses code  in the tests to manually exchange buffers via a FakeTransport class that is meant for that kind of testing.

**Comment by kozmaz87** [comment]
I will do this now.
