### ISSUE TITLE
[Retiming Delay Node] - Retiming delay node and multiple input sequences

### ISSUE THREAD

**Issue by kozmaz87** [ebu/ebu-tt-live-toolkit#360]
The retiming delay node is very straightforward and as such there is no safety check on the input. Assuming there are 2 sequences coming in both with sequence number 1 then the retiming delay node will replace the sequence identifier to its configured value and will create to documents with different content both having sequence number 1, which contradicts the spec.

**Comment by nigelmegitt** [comment]
I think we need either to constrain Retiming Delay Node to a single sequence or be able to specify a list of pairs of {input seqId, output seqId} in the configuration. For simplicity I would at first constrain the input to a single sequence.

**Comment by nigelmegitt** [comment]
A bit more background to this:

* There are two kinds of WebSocket connection:
  1. One where the thing making the connection sends data (documents) to the thing being connected to. This is done using a `/publish` URL.
  2. One where the thing making the connection receives data (documents) from the thing being connected to. This is done using a `/subscribe/` URL.
* When using a WebSocket **input** carriage mechanism with a `listen` config option, any number of upstream nodes can connect to the configured URL prefix with a `/[sequence_id]/publish` suffix and push sequences to the node in question. This applies not just to Retiming Delay Nodes, but any node configured like this.
* For passive nodes that don't do any processing but just pass the incoming sequence on, like a Buffer Delay node or a Distributor, this is fine because the outgoing connection can be based on the incoming sequence identifier.
* For nodes that do some processing, like a Retiming Delay Node, or a Resequencer, they are required to produce output with a sequence identifier that is different from the incoming sequence identifier.
* When there's one incoming sequence and one outgoing sequence, this is fine.
* When there are multiple incoming sequences, we currently only allow one outgoing sequence identifier to be specified, but it is not always the case that only a single output sequence needs to be made. (in Handover Manager for example it is the case, but in Retiming Delay Node it is not).
* Some way to support the options or to constrain the inputs is needed, which is this issue.

**Comment by nigelmegitt** [comment]
I've just noticed that this is very closely related to #307 - in fact fixing #307 would likely resolve this issue too.
