### ISSUE TITLE
[UIP] create authorsGroupControlRequest input on ui

### ISSUE THREAD

**Issue by kozmaz87** [ebu/ebu-tt-live-toolkit#379]
We need a text input box to allow a subtitler to create a control request. This is just one simple text box and it should submit on Enter(via javascript)

**Comment by kozmaz87** [comment]
Ok first question: Do we want different ticket type support as well or control request only?

Then: sender - receiver fields... do we want to control them or would that clutter the ui?

Where should the input box be positioned? possible under the publish connection bit or maybe in a foreground popup?

**Comment by nigelmegitt** [comment]
> Ok first question: Do we want different ticket type support as well or control request only?

Since the UIP and test.html are effectively debug tools, show anything we get.

> Then: sender - receiver fields... do we want to control them or would that clutter the ui?

I don't actually know what they are for but if they're useful then we should allow them to be controlled. Bear in mind we do not know who the possible recipients are - that could be another message type "current online authors in group", with a way to say "here I am" after establishing a connection to the handover manager. This sounds like future work... But it would allow for a pull-down or selection interface on the recipients list, for example.

> Where should the input box be positioned? possible under the publish connection bit or maybe in a foreground popup?

Definitely not a popup. Apart from that I don't care much and we can tidy it to a preferred location later if we don't like the first place it gets put.

**Comment by kozmaz87** [comment]
I reckon in the control request scenario it is mostly a broadcast purpose rather than targeting the currently active contributor only. This means sender is probably not needed for it. I just added it to the generic message header because 99% of the time a message has 2 entities: a sender and a recipient. In the broadcast scenario recipient is pretty much everyone

**Comment by nigelmegitt** [comment]
I don't think sender is needed if we have sequence identifier, is it? The intended recipient(s) may be useful as a filtering device though for receivers of the message. I don't object to including sender though in case it is useful to have a human readable label.

**Comment by kozmaz87** [comment]
also sender DOES NOT get restamped with applied processing

**Comment by nigelmegitt** [comment]
> also sender DOES NOT get restamped with applied processing

That's true, but I've lost track of the relevance @kozmaz87 ?

**Comment by kozmaz87** [comment]
well it is one of those things to identify a contributor by after handover gives the message back to you and in case of a message you receive messages from the unselected sources as well as the selected one in handover so a possible authorsGroupSelectedSequenceIdentifier would not help us here...

Also I am wondering if I shouldn't just generate a UUID for sender and save it in local storage identifying that computer until the user changes it to something or generates a new uuid

**Comment by nigelmegitt** [comment]
Oh right sorry, by "applied processing" you weren't referring to `ebuttm:appliedProcessing` but to some processing that has been applied e.g. by a Handover Manager.

I don't see how the Handover Manager generating a UUID would help since the sender wouldn't know their own UUID!

My idea for an `authorsGroupSelectedSequenceIdentifier` is to use it to tunnel out of the Handover Manager the sequence ID selected as the source by the Handover Manager. Still not sure what is wrong with that...

**Comment by kozmaz87** [comment]
Not the handover manager. The UIP to fill the sender field with something by default that is unique and identifiable.

**Comment by nigelmegitt** [comment]
Why not put a text box so it can be entered, and if absent/empty just not put a sender in?

**Comment by kozmaz87** [comment]
Well that is the obvious choice. I tried to reduce the number of upfront questions we ask the user before they can start...

**Comment by nigelmegitt** [comment]
Seems fine for me to do this - we could use local storage to allow a "user profile" to be predefined and auto-fetched on page load if we want to be fancy.

**Comment by nigelmegitt** [comment]
This was done in #387.
