### ISSUE TITLE
Deprecate standalone scripts

### ISSUE THREAD

**Issue by EyalLavi** [ebu/ebu-tt-live-toolkit#443]
The standalone scripts have been superseded by `ebu-run` but they are still in the repo. They should be clearly marked as deprecated and/or removed completely.

**Comment by nigelmegitt** [comment]
I think it is worth just saying "last maintained on [date]" because they are still potentially useful examples of how to create the relevant objects directly rather than using the configuration. In other words, I would prefer not to remove them altogether, just to mark them as not being actively maintained any more.

**Comment by EyalLavi** [comment]
Do we need stronger wording since they are actually buggy?

**Comment by nigelmegitt** [comment]
Well I assume they weren't buggy when they were last maintained! Happy to say "we know this has subsequently been broken by other code changes but haven't spent any effort fixing it"...

**Comment by nigelmegitt** [comment]
v2.1.1 has added a notice at the top of all the standalone scripts explaining that they are no longer being maintained. This is enough for now I think.
