### ISSUE TITLE
graphviz dependency not documented

### ISSUE THREAD

**Issue by frans-ebu** [ebu/ebu-tt-live-toolkit#8]
I think graphviz needs to be installed in order to see the figures in the documentation correctly, but this is not clear from the README.md.

(Building sphinx gives a warning it cannot find the dot executable if the user has not installed it).

I see two options:
- [ ] install graphviz automatically (not easy to do platform independently?)
- [x] document in README.md that the user needs to install graphviz and add the location of the dot executable to the PATH

**Comment by gilbrechbuhler** [comment]
Okay so I just tested that now. In order for this to work, the user has to install graphviz to have the dot comment. On my ubuntu it was as easy as :

```
sudo apt-get install graphviz
make docs
```
And it worked, so maybe a part about that in the readme with a link to graphviz installation's doc (their site is quite slow right now, but I'll give a link as soon as I can)

I am not really windows savy, so I cannot really help for that.

**Comment by frans-ebu** [comment]
I can confirm the install of graphviz on Windows (7) was straightforward. The important other thing is to update the Path correctly (which the installer no longer does).

I have suggested an updated readme text: https://github.com/ebu/ebu-tt-live-toolkit/blob/graphviz_dependency/README.md (but forgot to close this issue from the commit, sorry).

**Comment by frans-ebu** [comment]
I guess we could better close this one when the merge is approved. I will use a label to signal this one should be OK now.

**Comment by nigelmegitt** [comment]
I'm confused by the label - there's no pull request to merge for this issue, so what's ok to merge?

If there's a related commit please could you reference it in a comment here @frans-ebu so that we can see it more easily?

By the way, I see no problem in `make docs` downloading and installing required components as long as they don't break the licence requirements - in general `make` does fetch and install dependencies.

**Comment by frans-ebu** [comment]
@nigelmegitt you are right.

**Labels**
Basically I am wondering how to signal I believe this issue can be closed, without closing it as others (e.g. you) have not reviewed it yet. I thought the merge request (when we have more commits ready to be merged) may be that review point. Happy to use any better wording/workflow.

**The commit**
https://github.com/ebu/ebu-tt-live-toolkit/commit/d41d7584d866497082a7bf05f5e8ab22f56c2afd

**Make solution**
Ok, I see we could make a different make and make.bat, as we do for the rest.

**Comment by nigelmegitt** [comment]
I don't see why we shouldn't simply create a branch with the fix for this issue and a pull request to merge it, after which the issue can be closed (automatically if the PR or commit says it will fix the issue).

In this case I see there is a graphviz_dependency branch for it, so the thing to do is, when the fix is ready to review, make a pull request referencing this issue, and then everyone will know to review it. Maybe I'm missing something?

**Comment by nigelmegitt** [comment]
By the way I've just updated the README to include a graphviz install line, at commit 4ad24f6.

**Comment by frans-ebu** [comment]
@nigelmegitt Yes, I agree with the branch.

But when there are many issues on the same topic, I feel it can be hard to see which ones need attention. Using a label *in review*, *fixed* or something like that can help understand it likely is solved. Pointing contributors that want to help on the less progressed ones.

Reversely anybody interested in reviewing issues about to be closed can find them as well.

**Comment by nigelmegitt** [comment]
Agreed, @frans-ebu - I'm happy to use labels like this in general; I was just confused by this one. A scheme I've used before is:

* Needs work - someone needs to work on the solution
* Awaiting Review - solution finished, needs review
* OK to merge - review complete, needs merge

One thing that's a bit awkward is that you can't automatically apply the same label both to the issue and the pull request, whereas in fact you often want that, because you might be looking at either the issue or the PR view.

**Comment by frans-ebu** [comment]
Agreed that would be useful.

I have updated the labels accordingly; for 'Needs work' my pref would be 'Help wanted', as you could argue any open issue needs work :)

**Comment by frans-ebu** [comment]
To get to 'OK to merge': do we want to add the install of Graphviz to make, or shall we keep that for a potential enhancement for future?

Personally I think that is enough, as we have clearly noted the dependency in the documentaiton and you get a warning in your sphinx installation process if you have the dot application not installed.

**Comment by nigelmegitt** [comment]
I think keep the dependency documented and don't auto-install because I haven't checked the licence implications (which we have for the other installed python components, by the way).

**Comment by frans-ebu** [comment]
good point

**Comment by nigelmegitt** [comment]
However, to get to 'awaiting review' we actually need a pull request!

**Comment by kozmaz87** [comment]
https://en.wikipedia.org/wiki/Graphviz

In this one stands the following:

    Graphviz is free software licensed under the Eclipse Public License.

**Comment by frans-ebu** [comment]
Mm... maybe this is a problem. I read in https://eclipse.org/legal/eplfaq.php#USEINANOTHER

> Does the EPL allow me to take the Source Code for a Program licensed under it and include all or part of it in another program licensed under the GNU General Public License (GPL), Berkeley Software Distribution (BSD) license or other Open Source license?
No. Only the owner of software can decide whether and how to license it to others. Contributors to a Program licensed under the EPL understand that source code for the Program will be made available under the terms of the EPL. Unless you are the owner of the software or have received permission from the owner, you are not authorized to apply the terms of another license to the Program by including it in a program licensed under another Open Source license.

But I see here https://hackage.haskell.org/package/graphviz

> graphviz is free software licensed under a 3-Clause BSD License.

I did not go more in-depth..

**Comment by nigelmegitt** [comment]
Happy to keep this as a separate dependency for now since it is documented. It's documentation, not a requirement for running the software, so I don't think we should impose anything stronger.
