### ISSUE TITLE
Display document text with timings 

### ISSUE THREAD

**Issue by EyalLavi** [ebu/ebu-tt-live-toolkit#94]
Create a text view of Part 3 document text with begin and end times (processing the resolved begin and end times algorithm correctly according to the Part 3 specification), i.e. Intermediate Synchronic Document time analysis. This is a subtask of the simple consumer. See #87

**Comment by kozmaz87** [comment]
This one is unclear to me... what do we want here? A UI of sorts?

**Comment by kozmaz87** [comment]
Still having no clue on this

**Comment by nigelmegitt** [comment]
The idea here was to do something in the text output of the simple consumer for verifying expected output without going to the effort of making EBU-TT-D. It would be an extension of the current code that logs, whenever a document arrives, which documents become superseded or cut off and what the cut-off times are, and logs the new document's times.

Then a further useful addition is for new documents when they come in to output in text to stdout the text contents of each ISD. So you get a text view of what the effective output is supposed to be without having to go through a whole convert and render stage.

It's all supposed to go on stdout, not in a complex UI. So the user can see the effect of new documents arriving and verify it is what was expected.

For example in the case that text is being cut short because availability time > earliest computed begin time, it should show that because the begin time of the ISD at the receiving side is later than what was expected when the document was sent.

**Comment by kozmaz87** [comment]
And how is this any better than the ones in the logs? Except maybe the one where we put out the ISD contents... I am trying to wrap my head around this... for the most of it it will result in the following:

  document_logger.info(msg)
  print(msg)

What is the point there?

**Comment by nigelmegitt** [comment]
Can you post a snippet of what that `msg` would look like?

**Comment by kozmaz87** [comment]
Ok after our discussion this means Whenever text content is detected new, discarded, activation change it should log them on the console with their new activation times. 

The thing with the document logger so far is not granular enough.
This output should be paragraph level printing. So it will give people an understanding what text should be appearing on screen.

**Comment by nigelmegitt** [comment]
Yes, the current logging is at a document level, or tells you what times have been activated/deactivated, but that's really hard to use for getting confidence in what's going on, or even for basic debugging. The proposal here is that the actual timed contents that are activated/deactivated are printed/logged, as a config option (I'd expect it to be used in the simple consumer when validating incoming data). For example it could be something a bit like:

```text
activation time changed begin=xxx end=yyy for element:
   div <-- this element's activation times have changed
   |--p
      |--span "the text"
      |--span "the next line"
```

This would help us to understand for example what content is displayed for less time than expected because of a late availability time, for example. It does not need to list all the ISDs for example.

**Comment by kozmaz87** [comment]
Ok with the current implememtation of the timeline I may not be able to tell you that it was the div whose timing was changed. But I will be able to tell you all the p elements whose activation changed.

**Comment by nigelmegitt** [comment]
OK that sounds good enough to start with.

**Comment by nigelmegitt** [comment]
I think you've done this one in configurator!
